//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonDataStore.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PocketMonstersEntities : DbContext
    {
        public PocketMonstersEntities()
            : base("name=PocketMonstersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHARACTERS> CHARACTERS { get; set; }
        public virtual DbSet<CLASSES> CLASSES { get; set; }
        public virtual DbSet<RANKING> RANKING { get; set; }
        public virtual DbSet<SPECIFICATIONS> SPECIFICATIONS { get; set; }
        public virtual DbSet<WEAKNESS> WEAKNESS { get; set; }
    }
}
