//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonDataStore.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPECIFICATIONS
    {
        public long ID { get; set; }
        public long CHARACTERID { get; set; }
        public long HEIGHT { get; set; }
        public long WEIGHT { get; set; }
        public long LIFEPOINTS { get; set; }
        public long ATTACK { get; set; }
        public long DEFENSE { get; set; }
        public long SPECIALATTACK { get; set; }
        public long SPECIALDEFENSE { get; set; }
        public long SPEED { get; set; }
    
        public virtual CHARACTERS CHARACTERS { get; set; }
    }
}
